config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get 'homes/about'
  resources :books, only: [:new, :create, :index, :show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	attachment :book_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
    	user_path(resource)
    end

    protected

    def configure_permitted_parameters
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user
	end

	def new
		@book = Book.new
	end

	def create
		@user = current_user
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id)
			flash[:success] = "投稿されました！"
	    else
	    	redirect_to book_path(@book.id)
			flash[:failure] = "投稿に失敗しました。"
		end
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect books_path
		end
	end
	private
	def book_params
		params.require(:book).permit(:title, :body, :book_image, :tag, :author, :company, :year)	
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@books = Book.all
	end
	
	def about
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/new.html.erb
<%= form_for(@book, url: books_path) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
    	<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
    	<ul>
    	<% @book.errors.full_messages.each do |message| %>
    	  <li><%= message %></li>
    	<% end %>
        </ul>
    </div>
  <% end %>
  <div class="row">
  	<div class="col-sm-2">
  		<%= f.file_field :book_image,class: 'img_field',style: 'display:none;' %> 
  		<%= attachment_image_tag @book, :book_image, fallback: 'no_image.jpg', onClick: "$('.img_field').click()", class: 'center-block img thumbnail img-responsive img_prev' %>
  	</div>
  	<div class="field">
  		<%= f.text_field :title %>	
  	</div>
  	<div class="field">
  		<%= f.text_area :body %>
  	</div>
  	<div class="field">
  		<%= f.text_field :tag %>	
  	</div>
  	<div class="field">
  		<%= f.text_field :author %>	
  	</div>
  	<div class="field">
  		<%= f.text_field :company %>	
  	</div>
  	<div class="field">
  		<%= f.text_field :year %>	
  	</div>
  	<%= f.submit "投稿" %>
<% end %>

  </div>

app/views/homes/index.html.erb
<header class="navbar navbar-inverse">
    <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span class="white">Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
           <li> <%= link_to  "Home", user_path(current_user.id), class:"glyphicon glyphicon-home" %></li>
           <li> <%= link_to  "Users", users_path, class:"glyphicon glyphicon-user" %></li>
           <li> <%= link_to  "Books", books_path, class:"glyphicon glyphicon-book" %></li>
           <li> <%= link_to  "logout",  destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %></li>
         <% else %>
           <li>
             <%= link_to "Home",root_path, class:"glyphicon glyphicon-home" %>
           </li>
           <li>
             <%= link_to "About", homes_about_path, class:"glyphicon glyphicon-link" %>
           </li>
           <li>
             <%= link_to "sign Up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %>
           </li>
           <li>
             <%= link_to "login", new_user_session_path, class:"glyphicon glyphicon-log-in " %>
           </li>
         <% end %>
      </ul>
    </nav>
    </div>
  </header>
<div class="row">
	<div class="col-lg-4 col-lg-offset-4">
		<h4><strong>ようこそ！EDU BOOKSへ！<br/ >
		教育・実践の学びをもっと充実させたい！<br/ >そんな願いを叶えます！</strong><br/ >
		<%= link_to "＞＞このサイトについて", homes_about_path %></h4>
	</div>
	<div class="a">
		<div class="b">
			<img class="c" src="assets/Top_page.jpg">
		</div>
				<div class="b">
			<img class="c" src="assets/Top_page2.jpg">
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= yield %>
  </body>
</html>